name: g123_schnell
description: Aplicativo de Busca de números telefonicos

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_cupertino_localizations: ^1.0.1
  http: ^0.12.2
  transparent_image: ^1.0.0
  side_header_list_view: ^0.0.4
  carousel_pro: ^1.0.0
  crypto: ^2.1.4
  story_viewer: ^0.0.15
  shared_preferences: ^0.5.10
  flutter_slidable: ^0.5.4
  badges: ^1.1.3
  photo_view: ^0.10.2
  splash_screen_view: ^1.0.3
  date_format: ^1.0.9
  flutter_open_whatsapp: ^0.1.2
  flutter_login: ^1.0.14
  social_media_buttons: ^0.1.2
  image_picker: ^0.6.7+17
  carousel_slider: any
  flutter_swiper : ^1.1.6
  url_launcher: ^5.5.0
  maps_launcher: ^1.2.2+2
  auth_buttons: ^0.0.4
  google_sign_in: ^4.5.9
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/paytm_logo.png
    - assets/uanotif_nomessage.png
    - assets/smartphone.png
    - assets/hand.png
    - assets/phone-charge.png
    - assets/gold.png
    - assets/iocl_tip.png
    - assets/train_help.png
    - assets/send_money.png
    - assets/money_transfer.png
    - assets/ic_passbook_header.png
    - assets/calendar_blue.png
    - assets/add_money_passbook.png
    - assets/book.png
    - assets/real.jpg
    - assets/gstbanner.png
    - assets/logo.png
    - assets/powered_by.png
    - assets/shopping-bagg.png
    - assets/shopping-bag.png
    - assets/satellite-dish.png
    - assets/qr-code.png
    - assets/delivery.png
    - assets/console.png
    - assets/bank.png
    - assets/airplane.png
    - assets/access.png
    - assets/placeholder_inapp_merchants.png
    - assets/home.png
    - assets/right-arrow.png
    - assets/facebook_icon.png
    - assets/academia.png
    - assets/trabalho.png
    - assets/google-maps.png

    - imagens/whatsapp.png
    - imagens/loading.gif
    - imagens/carrega_produtos.gif
    - imagens/telephone-pulse.gif
    - imagens/telefone_carregando.gif
    - imagens/semtelefone.png
    - imagens/logoempresaicone.png
    - imagens/iconesemfundo.png
    - imagens/logo_empresa.jpeg
    - imagens/imagemlogin.png
    - imagens/logo_empresa_icone-sem-fundo.png
    - imagens/loginimagem.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
